/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cadastropessoa;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Professor
 */
public class TelaCadPessoa extends javax.swing.JInternalFrame {
    TelaPrincipal telaPrincipal;
    private int posicao = -1;
    
    /**
     * Creates new form TelaCasPessoa
     */
    public TelaCadPessoa(TelaPrincipal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
        this.posicao = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pessoas");
        setPreferredSize(new java.awt.Dimension(300, 300));
        setVisible(true);

        jLabel1.setText("Nome");

        jLabel2.setText("Endereço");
        jLabel2.setToolTipText("");

        jLabel3.setText("Email");
        jLabel3.setToolTipText("");

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Listar Pessoas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("◀");
        jButton3.setToolTipText("Cadastro Anterior");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("▶");
        jButton4.setToolTipText("Cadastro Posterior");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Excluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(camposPreenchidos()){
            Pessoa pessoa = new Pessoa();
            pessoa.setNome(txtNome.getText());
            pessoa.setEndereco(txtEndereco.getText());
            pessoa.setEmail(txtEmail.getText());
            String mensagem = "";
            //se a variável posição == -1 gravar novo registro
            //senão (!=) atualizar registro
            
            //adicionar essa pessoa no array listaPessoas na tela principal
            if(posicao == -1){
                telaPrincipal.addPessoaLista(pessoa);
                mensagem = "Pessoa Cadastrada com Sucesso!";
            }else{
                telaPrincipal.atualizarPessoaLista(pessoa, posicao);
                mensagem = "Pessoa Atualizada com Sucesso!";
            }
            limparTela();
            posicao = -1;
            JOptionPane.showMessageDialog(null, mensagem);
        }else{
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        listarPessoas();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        List<Pessoa> lstPessoa = telaPrincipal.getListaPessoa();
        posicao++;
        if(posicao < lstPessoa.size()){
            Pessoa pessoa = lstPessoa.get(posicao);
            //posicao++;
            txtNome.setText(pessoa.getNome());
            txtEndereco.setText(pessoa.getEndereco());
            txtEmail.setText(pessoa.getEmail());
        }else{
            JOptionPane.showMessageDialog(null, "Não há mais Cadastros");
            posicao = -1;
            limparTela();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        List<Pessoa> lstPessoa = telaPrincipal.getListaPessoa();
        posicao--;
        if(posicao > -1){
            Pessoa pessoa = lstPessoa.get(posicao);
 
            txtNome.setText(pessoa.getNome());
            txtEndereco.setText(pessoa.getEndereco());
            txtEmail.setText(pessoa.getEmail());
        }else{
            JOptionPane.showMessageDialog(null, "Não há mais Cadastros");
            posicao = -1;
            limparTela();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        List<Pessoa> lstPessoa = telaPrincipal.getListaPessoa();
        if (posicao < 0 || posicao >= lstPessoa.size()){
            JOptionPane.showMessageDialog(null, "Não há nenhum cadastro");
            return;
        }
        int resposta = JOptionPane.showConfirmDialog(null, 
                "Deseja realmente excluir este cadastro?", 
                "Confirmação", JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION){
            lstPessoa.remove(posicao);
            if (lstPessoa.isEmpty()){
                posicao = -1;
                limparTela();
            }else{
                if (posicao >= lstPessoa.size()){
                    posicao = lstPessoa.size() -1;
                }
                mostrarPessoa(posicao);
            }
            JOptionPane.showMessageDialog(null, "Cadastro Excluído com Sucesso");
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
    private void limparTela(){
        txtNome.setText("");
        txtEndereco.setText("");
        txtEmail.setText("");
        txtNome.requestFocusInWindow();
    }
    
    //método para exibir todas as pessoas da lista
    private void listarPessoas(){
        List<Pessoa> lstPessoa = telaPrincipal.getListaPessoa();
        String texto = "";
        for(Pessoa p: lstPessoa){
            //+= --> texto = texto + concatenar 
            texto += p.toString() + "\n ----------------------------- \n";
        }
        JOptionPane.showMessageDialog(null, texto);
    }

    private boolean camposPreenchidos() {
        boolean resposta = true;
        //vamos validar os campos
        if(txtNome.getText().length() == 0){
            resposta = false;
        }
        if(txtEndereco.getText().length() == 0 && resposta){
            resposta = false;
        }
        if(txtEmail.getText().length() == 0 && resposta){
            resposta = false;
        }
        return resposta;
    }
    
    private void mostrarPessoa(int pos){
        Pessoa pessoa = telaPrincipal.getListaPessoa().get(pos);
        txtNome.setText(pessoa.getNome());
        txtEndereco.setText(pessoa.getEndereco());
        txtEmail.setText(pessoa.getEmail());
    }
}
